Fix several compiler errors and warnings
Errors:
  error: a space is required between consecutive right angle brackets (use '> >')

Warnings:
  Shadow variable declarations, unused variables